POST http://127.0.0.1:5001/loppem-adf69/europe-west1/addPaymentAndConfirm http/1.1
content-type: application/json

{
  "studentId": "eVdASYJLguJqjPrNLjsp",
  "paymentAmount": 1220.0,
  "paymentDate": "01-01-2020",
  "paymentComplete": true
}
