exports.validTemporaryStudent = {
  'sitelanguage': 'nl',
  'language': 'english   ',
  'period': 'august   ',
  'firstNameStudent': 'Joske   ',
  'lastNameStudent': 'Vermeulen',
  'gender': 'boy',
  'birthday': '2020-01-01',

  'firstNameParent': 'Mario',
  'lastNameParent': 'Vermeulen',
  'email': 'onsmario@gmail.fake.com',
  'relation': 'yes please',
  'street': 'Trammezandlei',
  'houseNr': '122',
  'busNr': '',

  'city': 'Schoten',
  'zipCode': '2900',
  'gsm': '0412/121212',
  'gsm2': '',

  'nameSchool': 'école de test',
  'streetSchool': 'rue de test',
  'houseNrSchool': '1',
  'busNrSchool': '',
  'citySchool': 'Bruxelles',
  'zipSchool': '1000',
  'titleProfSchool': 'Mr',
  'nameProfSchool': 'François',
  'yearsSchool': '6',
  'hoursSchool': '1',
  'immersionSchool': 'true',
  'reportSchool': null,

  'apportedStudent': 'false',
  'contact': 'euhm',
  'additionalInfo': '<script>alert(\'test\')</script>',
  'foodInfo': 'Hoe meer hoe beter',
  'interest': 'Node.JS',
  'acceptPictures': false,
  'acceptTerms': true,
};

exports.validStudent = {
  'sitelanguage': 'nl',
  'language': 'english   ',
  'period': 'august   ',
  'firstNameStudent': 'Joske   ',
  'lastNameStudent': 'Vermeulen',
  'gender': 'boy',
  'birthday': '2020-01-01',

  'firstNameParent': 'Mario',
  'lastNameParent': 'Vermeulen',
  'email': 'onsmario@gmail.fake.com',
  'relation': 'yes please',
  'street': 'Trammezandlei',
  'houseNr': '122',
  'busNr': '',

  'city': 'Schoten',
  'zipCode': '2900',
  'gsm': '0412/121212',
  'gsm2': '',

  'nameSchool': 'école de test',
  'streetSchool': 'rue de test',
  'houseNrSchool': '1',
  'busNrSchool': '',
  'citySchool': 'Bruxelles',
  'zipSchool': '1000',
  'titleProfSchool': 'Mr',
  'nameProfSchool': 'François',
  'yearsSchool': '6',
  'hoursSchool': '1',
  'immersionSchool': 'true',
  'reportSchool': null,

  'apportedStudent': 'false',
  'contact': 'euhm',
  'additionalInfo': '<script>alert(\'test\')</script>',
  'foodInfo': 'Hoe meer hoe beter',
  'interest': 'Node.JS',
  'acceptPictures': false,
  'acceptTerms': true,
};

exports.validPayment = {
  'studentId': 'REPLACE_ME',
  'paymentAmount': 1220.0,
  'paymentDate': '01-01-2020',
  'paymentComplete': true,
};
